### ISSUE TITLE
Nginx configuration fails to load the SonarQube navigation bar after upgrade to 5.6 version

### ISSUE THREAD

**Issue by SachinKSingh28** [Accenture/adop-nginx#25]
This issue is also mentioned in the adop-sonar pull request to upgrade SonarQube.

https://github.com/Accenture/adop-sonar/pull/11

This issue is basically due to the kibana proxy rule in sites-enabled file. 

`    location ~* /bundles/.* {
        proxy_pass         http://kibana:5601;
    }
`

**Comment by m4m51m** [comment]
Change `location /sonar` to `location ^~ /sonar` solves the issue (see #29)

**Comment by mlushpenko** [comment]
Confirming that issue is solved

**Comment by svscorp** [comment]
Fixed in #29
