### ISSUE TITLE
Documentation not reflecting correct image name

### ISSUE THREAD

**Issue by gogodi91** [Accenture/adop-nginx#30]
adop/nginx:VERSION is not the correct tag to be pulled. This should be replaced with accenture/adop-nginx:VERSION

**Comment by RobertNorthard** [comment]
@gogodi91 the documentation has been updated. See PR 31.

**Comment by RobertNorthard** [comment]
Closing. Issue fixed in PR https://github.com/Accenture/adop-nginx/pull/31
