### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by ppferrari** [Accenture/adop-nginx#37]
Hi,

we're facing some issue while trying to upload a 250MB package to Nexus.
The issue is probably caused by the client_max_body_size nginx option set to 100M.

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by RobertNorthard** [comment]
Thanks @PPFerrari for raising this.

The Nexus [documentation](http://books.sonatype.com/nexus-book/pdf/nxbook-pdf.pdf) also suggests a 1G client max body size. 

Are you happy to make this change?  I would be happy to review.

**Comment by PPFerrari** [comment]
Sure! I'll make a pull request by the end of the day.

**Comment by PPFerrari** [comment]
The PR #38 has been merged to the master branch. Is it possible to update also the docker image, so the new client_max_body_size is set to 1G also when installing ADOP with the quickstart.sh?

**Comment by dsingh07** [comment]
Hi @PPFerrari 
Could you make an accompanying PR to adop-docker-compose to update the Nginx image tag? We will tag and release the new image with your changes, and it can be rolled out via that PR.

**Comment by svscorp** [comment]
@PPFerrari it is in the image starting from 0.3.1

**Comment by svscorp** [comment]
@PPFerrari @dsingh07 added to adop-docker-compose PR: Accenture/adop-docker-compose#249
