### ISSUE TITLE
Where is the integration part for the nginx with the devops tools on the dashboard?

### ISSUE THREAD

**Issue by jinrangcui** [Accenture/adop-nginx#50]
Hi Engineers, this is Tracy from DevOps team, as we know, after login to the nginx portal, when redirecting to the other tools such as jenkins, gitlab..., we need to input the user credentials one more time;
is it possible for one just login to the nginx portal one time and the other tools will share the user session?
if yes, which part should I update for this image? thank you!

**Comment by RobertNorthard** [comment]
Hi @jinrangcui 

Thanks for raising an issue.

Yes it is possible and this is how the ADOP/C platform works. 

A brief overview of how this works:
- ADOP/C platform authentication is offloaded to the adop-nginx proxy
- Once a user has successfully logged in (via the credential prompt) the user can access the other tools in the platform without double-login
- This works as the tools consume the Authorization header passed down from the proxy 

We are aware that there is an issue with double-login for Gerrit.

Please can you let me know what error you are having? 

Are you using aodp-nginx container with the ADOP/C platform?

Kind regards,

Robert

**Comment by RobertNorthard** [comment]
Hi @jinrangcui 

No worries. If you require any help please feel to raise another GitHub issues. I will close this one.

Kind regards,

Robert
